Add "My Recent Works" and "About Me" Sections
limavfabio/my-portfolio-old pull request #2
Opened 2022-06-30 21:40 UTC by limavfabio

This branch Adds "My Recent Works" and "About Me" Sections to the My-Portfolio project following HTML and CSS best practices and Microverse conventions.

2022-06-30 23:27 UTC, omarsalem7 requested changes
Hi @limavfabio 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Descriptive pull request ✔️
- No linter errors ✔️
- Descriptive commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 23:27 UTC, omarsalem7 commented on index.html
> +      <div class="text">My Recent Works</div>
- [ ] Kindly use header tag `hx` to improve SEO.

2022-06-30 23:27 UTC, omarsalem7 commented on index.html
> +      <div class="project-title">Multi-Post Stories</div>
- [ ] As stated above use `hx` fro all title for the project to improve SEO.

2022-06-30 23:27 UTC, omarsalem7 commented on index.html
> +      <div class="description">A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown p
- [ ] Kindly use `<p>` to build a good structure to improve SEO

2022-06-30 23:27 UTC, omarsalem7 commented on index.html
> +      </div>
- [ ] This should be a list `ul` and each of them a `li` and for the rest projects

2022-06-30 23:27 UTC, omarsalem7 commented on index.html
> +    <div class="title">About Me</div>
- [ ] Kindly use `hx` as stated before for title

2022-06-30 23:27 UTC, omarsalem7 commented on index.html
> +    <div class="description">Hello I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a proje
- [ ] Kindly us `<p>` instead of `div` as stated before

2022-06-30 23:27 UTC, omarsalem7 commented on index.html
> +    <div class="button">Get My Resume</div>
- [ ] Kindly use button or `<a>` for buttons and follow the button styling: Active and Hover.
![image](https://user-images.githubusercontent.com/53402600/176794552-51077e9f-f96a-4690-8af4-145e04c725f8.png)

2022-07-01 14:06 UTC, mmsesay approved these changes
Hi @limavfabio, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 14:20 UTC, merged